Development
Grandmagic13/RPGManager pull request #51
Opened 2017-03-22 12:48 UTC by Pluci

@Grandmagic13  Kérlek nézd át, mert teljesen átdolgoztam a Languages implementálását.

- created new MultipleFieldsGetterSetterLanguages
- created new Fields.LANGUAGES
- created new Fields.LANGUAGES_SETTER
- created new Languages enum and LanguagesSetter class
- modified junit tests 
- write some modification in Background enum to get default languages values for each backgrounds

2017-03-22 14:13 UTC, Grandmagic13 requested changes
- Nem tesztelsz malformed inputra sehol.
- Nem teszteled az általad megírt content helyességét (parametrizált teszt)
- Nem teszteled hogy ki lehet -e törölni a default kiajánlott nyelveket a languages átállításával
- Nem teszteled background váltásnál hozzáadja -e az új background ismert nyelveit
- És még ki tudja mit nem fedsz tesztekkel, hiszen kapásból én sem fogom tudni még mit kéne megnézni ezen, ezért lett volna nagyon hasznos ha TDDzel és a tesztjeidhez fejleszted hozzá a production kódot.
- Elsunnyogtad a TDDzést, és ezért van kb. 3 teszted amiből az egyik le sem fut! Ergo 2 teszttel próbálod fedni a commitodat. Ettől tele van az egész dead code-dal meg felesleges, szemantikailag hibás kóddal. Ezt az egyetlen megjegyzést kivételesen nem konstruktív megjegyzésnek szánom hanem szemrehányásnak. 2 hétnyi munka után elvárnám hogy legalább fossá legyen tesztelve ha már betolod, még ha nem is feltétlen csinálja azt amit kéne.
- Hagytam az adott changeknél review commenteket, nézd végig, dolgozd be, a tesztkommenteket itt fenn pedig vedd nagyon komolyan légyszíves.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +import java.text.MessageFormat.Field;
ez az import mire kell?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Sokkal kevesebb language van mint background. Nem lenne egyszerűbb a Languagesben tárolni a hozzájuk tartozó backgroundokat? Kevésbé lenne kaotikus. Ráadásul nem kellene egy csomó fieldet hozzáadni meg a konstruktort sem bővíteni.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	private Background(final String text, BaseClasses[] baseClasses, Languages[] language) {
A languages tömb neve félrevezető: 'language'
Olyan mintha egy language-et tárolnál, pedig igazából többet tárolsz. Nem lehetne languages, vagy startingLanguages vagy valami olvashatóbb?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		characterSheet.setData(Fields.LANGUAGES, this.language);
Amikor a Background objektum beállítja magát, miért írja felül a már beállított nyelveket? Mondok egy példát: Összeraktam egy karakterlapot amiben felvettem a nyelvek közé a dwarf nyelvet, az elf nyelvet meg a trade tongue-ot. Átállítom a backgroundomat Qunari Tal-Vashothra és ilyenkor besetteled a qunlatot, meg a trade tongue-ot, az előzőleg felvettek pedig eltűnnek! Ez hogy kerülhetett be? Ezt az esetet letesztelted?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +	LANGUAGES_SETTER(LanguagesSetter.class), LANGUAGES(HashSet.class, LANGUAGES_SETTER),
A languages-nek miért van szüksége tartalmazásra más field által? Nem implementálhatná a Languages simán a Set interface-t? (Lásd: Specializations review)

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(LanguagesSetter.class, new LanguagesSetter());
- A languages-nek miért van szüksége tartalmazásra más field által? Nem implementálhatná a Languages simán a Set interface-t? (Lásd: Specializations review)

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	public static Languages languages;
Ez sehol sincs inicializálva! Nem szól érte az eclipse? Ráadásul ezt mire használod? Miért tartalmaz Languages objektumot statikusan a Languages objektum? Ez mire kell?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import rpg_database.character_sheet.interfaces.MultipleFieldsGetterSetter;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.security.InvalidParameterException;
Ezt használod?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.AbstractCollection;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.ArrayList;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.Arrays;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.EnumSet;
És ezt? (hmm.... enumset, ez igéretesen hangzik. De az enum önmagában set... ez mire kellett?)

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.HashMap;
És ezt használod?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.HashSet;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.List;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.Set;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import rpg_database.character_sheet.interfaces.CustomSetter;
És ezt?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	ELVISH("Elvish"), QUNLAT("Qunlat"), ORLESIAN("Orlesian"), RIVAINI("Rivaini"), TEVENE("Tevene"), ANCIENT_TEVENE("Ancient Tevene");
- A ciriane az milyen Dragon Age nyelv? Sosem hallottam róla.
- A `DWARVEN_LANGUAGES("Dwarven languages")` lehetne `DWARVEN_LANGUAGE("Dwarven language")`
- A `ELVISH("Elvish")` lehetne `ELVEN("Elven")`

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +	@Override
Ha nem használod a `setSelfValueByField`-et, akkor nem lenne egyszerűbb simán CustomSetter-t használni vagy egy Set-et implementáló class-t?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		return defaultLanguages;
Így olyan mintha az objektum mindig azt a Set-et adná vissza, hogy [ANDER, TRADE_TONGUE]. Nem lehetne a defaultokat meg az actual tárolt cuccokat külön kezelni? Ez baromira félreérthető

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		defaultLanguages = (HashSet<Languages>) value;
settelésnél a defaultLanguagesbe írsz bele? Nagyon félrevezető

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		defaultLanguages = new HashSet<Languages>();
A default értékekkel való feltöltés a characterSheet felelőssége. Miért nem ott történik, mint az összes többinél?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +import rpg_database.character_sheet.interfaces.CustomSetter;
Be van importálva 3 interfész. 2-t nem használsz.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +import java.util.List;
Ezt használod?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/interfaces/MultipleFieldsGetterSetterLanguages.java
> +public interface MultipleFieldsGetterSetterLanguages<DATA, DATATYPE> extends MultipleFieldsGetterSetter{
Ahhoz hogy Set-et adj vissza miért kell egy új interfész? Nem lett volna egyszerűbb implementálni a Set interfészt? Languages-be raksz egy HashSet-et és az Override-olt metódusokban a HashSet adattagod metódusait adod vissza. Miért kell neked setSelfValueByField ehhez? És getStoredValueByFields? Mire használod ezeket amiket egy Set interfész ne tudna?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		defaultLanguages.add(Languages.TRADE_TONGUE);
Ne nevezzük át inkább expectedLanguages-re? A másik naminggel együtt elég összezavaró.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		HashSet<Languages> language = defaultCharacterSheet.getData(Fields.LANGUAGES);
Ne nevezzük át inkább actualLanguages-re? Sokkal egyértelműbb.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		@Before
dead code. nem csinál semmit. szedd ki

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.Before;
dead code-hoz van importálva

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import rpg_database.character_sheet.exceptions.CoinOutOfBoundsException;
ezt mire használod?

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		@Rule
dead code. nem használod sehol

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.Rule;
dead code-hoz van importálva

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.rules.ExpectedException;
dead code-hoz van importálva

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		public void testSetLanguagesAntivanWayfarerExpectedFail(){
Ez biztos nem fog lefutni. Hol expecteled a tesztben az Exception dobását??? Lefuttattad te a tesztjeidet egyáltalán??? Ez tuti nem zöld!!! Ha nem zöld a teszt akkor nem pusholhatsz! Alap.

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			HashSet<Languages> language = characterSheet.getData(Fields.LANGUAGES);
Lehetne actualLanguage, hogy egyértelmű legyen

2017-03-22 14:13 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			HashSet<Languages> language = characterSheet.getData(Fields.LANGUAGES);
Lehetne actualLanguage, hogy egyértelmű legyen

2017-03-29 10:31 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +import java.text.MessageFormat.Field;
Törölve.

2017-03-29 11:09 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Igaz, átraktam az egészet, most már a languages tárolja ezeket az információkat.

2017-03-29 11:12 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		characterSheet.setData(Fields.LANGUAGES, this.language);
Ez direkt van így, ami hasonló elvű program volt annál én ezt szoktam meg, hogy ha base classot, backgroundot állítasz akkor resetel minden eddig beállított dolgot. Viszont átállítani át lehet a defaultokat ezután.

2017-03-29 11:13 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.security.InvalidParameterException;
Törölve.

2017-03-29 11:14 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.AbstractCollection;
Törölve.

2017-03-29 11:14 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.ArrayList;
Törölve.

2017-03-29 11:14 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.Arrays;
Törölve.

2017-03-29 11:14 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.EnumSet;
Feldobta amikor játszottam a fieldek beállításaival. Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.HashMap;
Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.HashSet;
Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.List;
Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import java.util.Set;
Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import rpg_database.character_sheet.interfaces.CustomSetter;
Törölve.

2017-03-29 11:15 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +import rpg_database.character_sheet.interfaces.MultipleFieldsGetterSetter;
Törölve.

2017-03-29 11:19 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	ELVISH("Elvish"), QUNLAT("Qunlat"), ORLESIAN("Orlesian"), RIVAINI("Rivaini"), TEVENE("Tevene"), ANCIENT_TEVENE("Ancient Tevene");
Ciriane, the language of the Ciriane tribe who first settled central Orlais. 
---> http://dragonage.wikia.com/wiki/Language <---
De töröltem, mert nincs olyan background ami használná. 

Módosítottam a többit ahogy kérted.

2017-03-29 11:21 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	public static Languages languages;
Törölve.

2017-03-29 11:22 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +import java.util.List;
Törölve.

2017-03-29 11:22 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +import rpg_database.character_sheet.interfaces.CustomSetter;
Törölve.

2017-03-29 12:47 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	ELVISH("Elvish"), QUNLAT("Qunlat"), ORLESIAN("Orlesian"), RIVAINI("Rivaini"), TEVENE("Tevene"), ANCIENT_TEVENE("Ancient Tevene");
Érdekes, ezt nem is néztem... Majd jól jön RPGhez.
Minden esetre azokat használd légyszi amik ebben vannak: https://www.dropbox.com/s/97viilhz6ya9zmx/Dragonage%20Core%20Rulebook.pdf?dl=0

2017-03-29 12:57 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		characterSheet.setData(Fields.LANGUAGES, this.language);
"hasonló elvű program" - mondanál egy példát?
"ezt szoktam meg, hogy ha base classot, backgroundot állítasz akkor resetel minden eddig beállított dolgot" - ha átállítasz egy base class-t vagy egy backgroundot, akkor megnézi hogy az általad indítványozott új base class/background kompatibilis -e a többi beállítással és ha nem az akkor hibát dob. Egyéb esetben pedig csak az módosul. Tehát nem értem hogy mire gondolsz pontosan, légyszi fejtsd ki.

És ok hogy a defaultokat át lehet állítani, csak idegesítő. Ha a kiajánlott default language felülcsapja a user által addig beállítottakat az a usernek idegesítő lesz, azt nem akarom. Akkor inkább oldjuk majd meg hogy frontend logikával feldob egy message boxot hogy "Do you want to add this language <backgroundDefaultLanguage>?" és akkor most ne is foglalkozz ezzel az extra viselkedéssel.

Vagy csak simán adja hozzá background váltásnál az adott új background default nyelvét ahhoz a sethez ami tartalmazza a már eddig hozzáadott nyelveket, hiszen ebben állapodtunk meg amikor ez a téma anno szóba került.

2017-03-29 13:26 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import java.security.InvalidParameterException;
Törölve.

2017-03-29 13:26 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.Before;
Törölve.

2017-03-29 13:40 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.Rule;
Törölve.

2017-03-29 13:40 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import org.junit.rules.ExpectedException;
Törölve.

2017-03-29 13:41 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import rpg_database.character_sheet.exceptions.CoinOutOfBoundsException;
Törölve.

2017-03-29 13:41 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		@Rule
Törölve.

2017-03-29 13:41 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		@Before
Törölve.

2017-03-29 13:44 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			HashSet<Languages> language = characterSheet.getData(Fields.LANGUAGES);
Done.

2017-03-29 13:46 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		public void testSetLanguagesAntivanWayfarerExpectedFail(){
assertNotEquals(expectedLanguage, actualLanguage);  <--- emiatt fog lefutni. 
Tudom, hogy át kell dolgozni...

2017-03-29 13:46 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			HashSet<Languages> language = characterSheet.getData(Fields.LANGUAGES);
Done.

2017-03-29 13:58 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +		public void testSetLanguagesAntivanWayfarerExpectedFail(){
Használj légyszi akkor @Rule-t és a hozzá tartozó függvényeket ahogy más unit test file-okban is használjuk. Találsz rá példát a forráskódban.

2017-03-29 18:02 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +	LANGUAGES_SETTER(LanguagesSetter.class), LANGUAGES(HashSet.class, LANGUAGES_SETTER),
Megváltoztatva Set-re.

2017-03-29 18:03 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(LanguagesSetter.class, new LanguagesSetter());
Done.

2017-03-29 18:05 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		defaultLanguages = new HashSet<Languages>();
Már ott történik. Done.

2017-03-29 18:05 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		return defaultLanguages;
Átírva.

2017-03-29 18:07 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +		defaultLanguages = (HashSet<Languages>) value;
Törölve.

2017-03-29 18:07 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +	@Override
Törölve.
CustomSetter implementálva.

2017-03-29 18:07 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/interfaces/MultipleFieldsGetterSetterLanguages.java
> +public interface MultipleFieldsGetterSetterLanguages<DATA, DATATYPE> extends MultipleFieldsGetterSetter{
Törölve.

2017-03-29 18:08 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		defaultLanguages.add(Languages.TRADE_TONGUE);
Done.

2017-03-29 18:08 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		HashSet<Languages> language = defaultCharacterSheet.getData(Fields.LANGUAGES);
Done.

2017-03-29 19:58 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
No, akkor abban egyeztünk meg hogy csinálj statikus privát LanguagesSet-eket, amiket viszont berakosgathatsz már a Background enumok konstruktoraiba. Pl ilyesmik, hogy:

```java
...TAL_VASHOTH("Tal-Vashoth", playAs_Mage_Warrior_Rogue(), TRADE_TONGUE_QUNLAT), ...

private static final LanguagesSet TRADE_TONGUE_QUNLAT = new LanguagesSet(Languages.TRADE_TONGUE, Languages.QUNLAT);
```

2017-03-29 20:00 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		characterSheet.setData(Fields.LANGUAGES, this.language);
Oks, na a telefon után meggyőztél. Akkor itt az a megoldás hogy minden alkalommal amikor új backgroundot állítunk be, törlöd a LanguagesSet-jét a CharacterSheet-nek, és újra feltöltöd az adott background nyelveivel

2017-03-29 20:01 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSetter.java
> +	@Override
Végül aztán nem vagyok biztos benne hogy neked ez úgy kelleni fog ahogy azt telefonon megbeszéltük. Minden esetre ha nem lesz rá szükséged akkor utólag majd gyomláld ki :)

2017-03-30 18:37 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Ez így nem lesz jó, mert ehhez statikus konstruktor kéne, de azt meg nem engedi az enum definiálni.

2017-03-30 19:05 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		characterSheet.setData(Fields.LANGUAGES, this.language);
Ezt megoldottam.

2017-03-30 19:25 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
francokat kell, hát a mostani konstruktora sem az. csinálj egy másik konstruktort ami fogad még +1 paramétert, ami egy LanguagesSet

2017-03-30 19:28 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Mondjuk így:
```java
private Background(final String text, BaseClasses[] baseClasses, LanguagesSet languages) {
		this.languages = languages;
		Background(text, baseClasses);
	}
```

2017-03-30 22:49 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
A background helyett this kell. Viszont így meg  nem engedi, hogy a languages final legyen. :S

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-03-30 23:12 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	ANDER_SURVIVOR("Ander Survivor", playAs_Mage_Warrior_Rogue(), new Languages[] {Languages.ANDER,Languages.TRADE_TONGUE }),
Hozd fel légyszi vasárnap és akkor megoldjuk. Addig maradhat private final. Vagy ha nincs kedved vasárnapig várni vele akkor vagy statikus metódusokat írsz vagy google it + stackoverflow.

2017-04-03 11:43 UTC, Grandmagic13 requested changes
Na ez sokkal jobban fest mint az előző! Viszont azért van benne rengeteg apró hiba. Hagytam megjegyzéseket, hogy hogyan tudsz fejleszteni a kódodon. Egy igazán súlyos hiba van amit látok, a setData-t szerintem nem használod rendeltetésszerűen, azt nagyon fontos lenne megjavítanod. Egyébként ha bedolgozod a review kommenteket akkor fasza lesz.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		this.text = generateEnumText(this.name());
A két konstruktorból ki lehetne emelni egy privát függvénybe a text, baseClasses és language értékadását, hisz mindkettő esetén ugyanaz történik.
pl.:
```java
private void initializeMandatoryFields(BaseClasses[] baseClasses, final LanguagesSet languages){
    this.text = generateEnumText(this.name());
    this.baseClasses = new ArrayList<>(Arrays.asList(baseClasses));
    this.language = languages;
}

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	private final LanguagesSet language;
ez lehetne 'languages' 'language' helyett. Mert ez szerintem félrevezető.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		LanguagesSet thisLanguages = new LanguagesSet();
Itt elvileg egyébként van copykonstruktor, szóval nyugodtan lehet
```java
LanguagesSet thisLanguages = new LanguagesSet(this.language);
```
legalábbis itt ezt írja:
http://stackoverflow.com/questions/7537361/copying-sets-java

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		}else {
Ez csak egy apróság, de légyszi használd az eclipse autoformatterét :) Ha kell segítek beállítani. Egy csomó felesleges diffet ki lehet vele kerülni, ha ugyanazt a formattert használjuk.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +import java.util.HashSet;
```java
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
```

Ezeket használja az osztály?

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +import java.util.HashSet;
Ezt még használja a Fields?

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +		this.text = text;
Itt használhatod a CharacterSheetCommon-nak a generateEnumText metódusát

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	public final static LanguagesSet QUNLAT_TEVENE_TRADE = new LanguagesSet(Languages.TEVENE,Languages.QUNLAT,Languages.TRADE_TONGUE);
```java
public final static LanguagesSet QUNLAT_TEVENE_TRADE = new LanguagesSet(Languages.TEVENE,Languages.QUNLAT,Languages.TRADE_TONGUE);
```

Van olyan background enum ami ezt használja? Vagy tesztben használod? Ha tesztben használod, akkor légyszi abban az osztályban emeld ki. A teszthez tartozó konstansokat nem feladata a Languagesnek tárolni.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	WAKING_SEA_RAIDER(playAs_Warrior_Rogue(), ANTIVAN_TRADE);
A Waking Sea Raidernél add csak a Trade Tongue-ot. Azt hogy antívai, rivaini, vagy orlézül fog beszélni azt a frontendlogikánál kell majd felkínálnunk szerintem. Cserébe légyszíves vegyél fel erre a waffle-ben egy issue-t hogy később ne merüljön a feledés homályába.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	//TODO WAKING_SEA_RAIDER' default languages depends on the land where he is from, can be Antivan, Rivaine or Orlesian
Erre a megfelelő helyen reflektáltam, ha megoldottad akkor ezt a kommentet légyszi töröld. (viszont jó hogy bennehagytad, így legalább kiderült hogy ez még nem készült el)

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		LanguagesSet temp = (LanguagesSet) characterSheet.characterData.get(Fields.LANGUAGES);
a 'temp' lehetne inkább 'characterSheetLanguages' vagy valami kifejező

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +			for (Languages languages : languagesSet) {
itt a 'languages' nevű ideiglenes változód neve félrevezető. lehetne csak 'language'.

Btw. ezt te írtad extrába? ez dícséretes.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultLanguagesForEachBackgroundUnitTests.java
> +				{ Background.ANDER_SURVIVOR, new LanguagesSet(Languages.ANDER, Languages.TRADE_TONGUE) },
Ezeket a language kombinációkat ki lehetne emelni egy testData classba. Ha minden mással kész leszel, akkor ezzel kapcsolatban légyszi keress meg és akkor elmagyarázom hogy mire gondolok. Nyilván ez már csak kódszépészkedés, de hasznos kódszépészkedés.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultLanguagesForEachBackgroundUnitTests.java
> +		testCharacterSheet.setData(Fields.BASECLASS, background.getAllowedBaseClasses().get(0));
kódszépészkedés No.2:
Ezt a `background.getAllowedBaseClasses().get(0)`-t ki lehetne emelni egy privát függvénybe amiből kiderül hogy mit is akarsz ezzel csinálni.
pl.:
```java
private getFirstValidBaseClassByBackground(Background background){
    return background.getAllowedBaseClasses().get(0);
}
```

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		defaultLanguages.add(Languages.TRADE_TONGUE);
Done? én nem látom. Az expected actual-t jobban preferálom még mindig :)

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		LanguagesSet temp = (LanguagesSet) characterSheet.characterData.get(Fields.LANGUAGES);
Ezt a file-t miért committoltad? Van erre még szükség? Nem kellett volna ezt kitörölni?

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		temp.addAll(this);
A setData-nak mindig felül kell írnia az előző objektumot az átadott új objektummal. Ne a setData-val adjunk hozzá az előzőhöz....
Cserébe látom hogy ezt a tesztekben is így használod. Ha hozzá szeretnél adni a nyelvekhez akkor ahhoz kérd el a LanguagesSet objektumot és ahhoz adj hozzá a tesztben majd légyszi.

2017-04-03 11:43 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			characterSheet.setData(Fields.LANGUAGES, temporaryLanguages);
Na ezt említettem feljebb, hogy ne a setData-val adjunk hozzá a LanguagesSet-hez, azzal íródjon felül. A setternek ez a lényege sajnos, hogy nem hozzáad hanem felülírja az előzőt. Egyéb esetben később nem tudnánk kívülről törölni, hisz az is úgy menne hogy egy üres LanguagesSet-et állítanánk setData-val. Ez szerintem fontos.

Cserébe kérd ki a Languages objektumot, esetleg akár másold le, adj hozzá és azt setteld setData-val.

2017-04-03 18:26 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	WAKING_SEA_RAIDER(playAs_Warrior_Rogue(), ANTIVAN_TRADE);
Kész.

2017-04-03 18:26 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	private final LanguagesSet language;
Átnevezve.

2017-04-03 19:26 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		this.text = generateEnumText(this.name());
Ezt ebben a formában nem fogadja el a fordító.

2017-04-03 19:45 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		LanguagesSet thisLanguages = new LanguagesSet();
Szerintem ez csak generikusoknál működik, ellenben a LanguagesSet csak implementálja a Set interfacet, de ettől nem lesz generikus osztály.

2017-04-03 19:45 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +import java.util.HashSet;
Törölve.

2017-04-03 19:47 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		}else {
Oké, akkor majd segíthetsz beállítani.

2017-04-03 19:47 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +import java.util.HashSet;
Törölve.

2017-04-03 19:49 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	public final static LanguagesSet QUNLAT_TEVENE_TRADE = new LanguagesSet(Languages.TEVENE,Languages.QUNLAT,Languages.TRADE_TONGUE);
A WAKING_SEA_RAIDER használta, de már töröltem azóta. Lásd első comment.

2017-04-03 19:52 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +		this.text = text;
Oké,

2017-04-03 19:52 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Languages.java
> +	//TODO WAKING_SEA_RAIDER' default languages depends on the land where he is from, can be Antivan, Rivaine or Orlesian
Törölve

2017-04-03 19:55 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		LanguagesSet temp = (LanguagesSet) characterSheet.characterData.get(Fields.LANGUAGES);
Megvan. Persze ez az osztály az összetartó kapocs a Languages és a CharacterSheet között.

2017-04-03 20:23 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		temp.addAll(this);
Módosítva. Ezt átírtam teljesen, mert így az addAll általi referencia átadásból később csak problémák lesznek.

2017-04-03 20:24 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +			for (Languages languages : languagesSet) {
Átirava. Szerintem a tiédről koppintottam.

2017-04-03 20:25 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultLanguagesForEachBackgroundUnitTests.java
> +				{ Background.ANDER_SURVIVOR, new LanguagesSet(Languages.ANDER, Languages.TRADE_TONGUE) },
Oké, akkor holnap keríthetünk rá sort.

2017-04-03 20:29 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultLanguagesForEachBackgroundUnitTests.java
> +		testCharacterSheet.setData(Fields.BASECLASS, background.getAllowedBaseClasses().get(0));
Megvan.

2017-04-03 20:36 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			characterSheet.setData(Fields.LANGUAGES, temporaryLanguages);
Most már felülírja az egészet a set data. Ha így sem jó szerinted akkor majd szóban futtassunk le egy eszmecserét, mert értem is meg nem is, hogy miért nem tartod jónak.

2017-04-03 21:40 UTC, Grandmagic13 requested changes
Átnéztem. Írtam.

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		this.text = generateEnumText(this.name());
igaz. és ha így csinálod?
```java
private Background(BaseClasses[] baseClasses, final LanguagesSet languages){
                this(baseClasses, languages, new HashSet<Background>());
  	}
}

private Background(BaseClasses[] baseClasses, final LanguagesSet languages, HashSet<Background> restrictedBackgrounds){
		this.text = generateEnumText(this.name());
        	this.baseClasses = new ArrayList<>(Arrays.asList(baseClasses));
		this.languages = languages;
		this.restrictedBackgrounds = restrictedBackgrounds;
	}
}
```

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +		LanguagesSet thisLanguages = new LanguagesSet();
ezt megnézted, vagy csak szerinted van így? A copyconstruktor nem függ attól hogy generikus az osztály vagy sem.
Amúgy a `characterSheet.characterData.remove(Fields.LANGUAGES);`-ot kiszedheted. A put felülírja az előző értéket. (Bocs erre sajnos én is csak ma jöttem rá, de egy sorral kevesebb :) )

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		}else {
Egyelőre ha teheted, mielőtt végleg bezársz egy file-t, nyomj egy Ctrl+Shift+F-et, addig tudsz úgy formattolni. Szerdán belőjük, ok?

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultLanguagesForEachBackgroundUnitTests.java
> +				{ Background.ANDER_SURVIVOR, new LanguagesSet(Languages.ANDER, Languages.TRADE_TONGUE) },
Nyugodtan csörrenj rám, ha itthon vagyok akkor elmagyarázom.

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Background.java
> +	WAKING_SEA_RAIDER(playAs_Warrior_Rogue(), ANTIVAN_TRADE);
A SEHERON_CONVERT-nél kivettél 2 nyelvet. A WAKING_SEA_RAIDER viszont nem változott.

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/interfaces/MultipleFieldsGetterSetterLanguages.java
> +public interface MultipleFieldsGetterSetterLanguages<DATA, DATATYPE> extends MultipleFieldsGetterSetter{
Még mindig látom. Biztos hogy törölted? A törlést is hozzá kell adnod az indexhez és pusholnod kell.

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +			characterSheet.setData(Fields.LANGUAGES, temporaryLanguages);
Én nem látom hogy átírtad volna, hagyok ott egy commentet

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/LanguagesUnitTests.java
> +import java.security.InvalidParameterException;
Én még mindig látom itt. Biztos hogy mindent felpusholtál?

2017-04-03 21:40 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		LanguagesSet characterSheetLanguages = (LanguagesSet) characterSheet.characterData.get(Fields.LANGUAGES);
Ne haragudj de itt nem értem hogy mi történik. Az a languages változó ott mire kell? Meg a for ciklus? Azt írtad hogy megcsinálod ezt a függvényt úgy hogy a setData a ezzel a (this) LanguagesSet-tel felülírja az előzőt. Ehhez képest látom hogy még mindig kikéred az előzőt és ahhoz addolgatsz.

2017-04-04 08:19 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/LanguagesSet.java
> +		LanguagesSet characterSheetLanguages = (LanguagesSet) characterSheet.characterData.get(Fields.LANGUAGES);
Így nem tudok egyesével commenteket hagyni, úgyhogy majd rád csörgök este aztán megbeszéljük.

2017-04-06 15:00 UTC, Grandmagic13 requested changes
Hagytam egy kommentet, ha azt még kijavítod akkor a következő körben approve-olom és mehet be :) :+1:

2017-04-06 15:00 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/resources/GetDefaultLanguagesForEachBackgroundUnitTestsData.java
> +public class GetDefaultLanguagesForEachBackgroundUnitTestsData {
Ezt a classt érdemes lenne átnevezni 'LanguagesUnitTestData'-ra simán, mert az ebben lévő dolgokat később bármelyik languages-t tesztelő unit test-hez felhasználhatod. Ergo nem érdemes specifikusan egy unit test classhoz rendelni név szerint.

2017-04-06 15:06 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/resources/GetDefaultLanguagesForEachBackgroundUnitTestsData.java
> +public class GetDefaultLanguagesForEachBackgroundUnitTestsData {
Done.

2017-04-06 15:29 UTC, Grandmagic13 approved these changes
Approved.

2017-04-06 15:30 UTC, merged