Implemented 2 new enums, Armors and Shields.
Grandmagic13/RPGManager pull request #68
Opened 2017-04-11 21:10 UTC by Pluci

closes #19 

-New Fields like Armor_Type and Shields
-Added unit tests for Armors
-Added unit tests for Shields
-Modified BaseClasses to set default Armors
-Added default Armor and Shield for characterData

2017-04-11 22:38 UTC, Grandmagic13 commented
a closes kulcsszót elég a merge által felajánlott szövegdobozba beírni. onnan fogja tudni a waffle, hogy lezártad :)

2017-04-11 23:23 UTC, Grandmagic13 requested changes
Úgy látom hogy kicsit a ló másik oldalára estél (lásd Sheilds.java, cost) viszont összességében kevesebb megjegyzésem van hozzá mint a Languageshez, és a TDD-k jó irányba mutatnak :) Olvasd át, és légyszi javítsd őket. A Shieldsről pedig beszéljünk szerda este

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/BaseClasses.java
> +	WARRIOR(Armors.LIGHT_MAIL), ROGUE(Armors.LIGHT_LEATHER), MAGE(Armors.NONE);
- Warik heavy leathert kapnak alapjáratban tudtommal, viszont ez jó ötlet :)

- a NONE lehetne ROBE vagy CLOTH

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +	private final int cost;
Ez a cost biztos hogy kell? Karilapon nem igazán tüntetjük fel.... Félre ne érts, szerintem tök király hogy ennyire beleástad magadat a dologba, csak kicsit úgy érzem hogy a ló túloldalára estél :) Ebben a classban nem látom szükségét. Esetleg ha majd itemek costjával akarunk foglalkozni előjöhet, de akkor meg már valószínűleg más classba is raknánk, vagy interfészként implementáltatnánk minden item jellegű objektummal, vagy tudjaisten, de amíg nem lesz rá szükség, addig szerintem  felesleges. Esetleg tedd ki a costos implementációt egy külön branchre, hogy ha kell akkor meglegyen, de szerintem itt felesleges.

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/BaseClasses.java
> +	private final Armors armor;
Hívhatnád defaultArmor-nak, mert ez csak az amit kiajánlasz.

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(Armors.class, Armors.LIGHT_MAIL);
Ezt is meg tudnád változtatni HEAVY_LEATHER-re?

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(Shields.class, Shields.NONE);
Shields egyelőre ne legyen, tedd ki egy local branchre vagy mentsd el másképp, lásd a Sheilds.java-hoz írt commentemet.

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		characterSheet.setData(Fields.ARMOR_TYPE, Armors.LIGHT_PLATE);
- itt a LIGHT_PLATE-et kiszervezheted lokális változóba, pl:
```java
Armors expectedArmor = Armors.LIGHT_PLATE;
characterSheet.setData(Fields.ARMOR_TYPE, expectedArmor);
....
```

- Így ha valami gebasz van vele, akkor csak egy helyen kell átírni

- Armor Training Talent befolyásolja egyébként h milyen armort hordhatsz szóval ezeket majd még meg kell módosítani ha lesznek talentjeink.... Erre (mármint hogy korrigálni kell majd az armor typeokat) (igen én is csak most jöttem rá) erre felvehetnél egy taskot :)

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(Armors.LIGHT_MAIL, actualValue);
ide is dobok egy kommentet hogy ki ne feledd: HEAVY_LEATHER

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testSetArmorForWarrior() {
Ezzel mit tesztelsz amit a testSetArmorTypeLightPlate nem tesztel?

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(-3, actualValue + Armors.class.cast(characterSheet.getData(Fields.ARMOR_TYPE)).getArmorPenalty());
- ```Armors.class.cast(characterSheet.getData(Fields.ARMOR_TYPE)).getArmorPenalty()``` helyett:
```java
characterSheet.<Armors>getData(Fields.ARMOR_TYPE)).getArmorPenalty()
```
és miért kell hozzáadnod a dexterity-hez? Nem elég simán a penalty értékét vizsgálni? A DEX itt amúgy is 0 nem?
- Az armor training ezt is befolyásolja, ugyanis a penalty-t csak speedre kapja a karakter ha van neki. Ez is átírásszagú a jövőben, érdemes rá taskot felvenni, vagy jelezni az előzőben ha azt már felvetted.

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testGetCostArmorForWarrior() {
A costról már írtam feljebb, természetesen megvitathatjuk a hasznát. Nyilván nem a teszttel kapcsolatban van kifogásom

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +	HEAVY_PLATE(10, -5, 150), LIGHT_LEATHER_DUSTER(3, 0, 15), TAILORED_LEATHER_DUSTER(4, 0, 45), NONE(0, 0, 0);
A NONE lehetne ROBE, vagy CLOTH

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testGetDefaultDefenseAnderSurvivor() {
"testGetDefaultDefenseAnderSurvivor" ez félrevezető. Semmi köze a Defense-hez (ami ugye dexből jön) lehetne "testGetDefaultArmorRating_HeavyPlate" nem beszélve arról hogy a többi számozott tesztet is hasonló logika alapján el tudod nevezni, nem fogom egyenként odaírni, de azokat a számozottakat nevezd el normálisan.

Egyébként erre egy parametrizált teszt lenne a legízlésesebb ahol nem csak szúrópróbaszerűen nézel meg egy-két értéket hanem az összes enumod default armor ratingjét végignyálazod. Pl. a heavy_leather-t nem látom ezek között de a light_mail-t sem.
Egyébként meg ehhez állítgatni is felesleges a karakterlapot. Végigtesztelheted az Armor.getArmorRatinggel....

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		assertEquals(Armors.LIGHT_MAIL, defaultCharacterSheet.getData(Fields.ARMOR_TYPE));
HEAVY_LEATHER

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Shields.java
> +package rpg_database.character_sheet;
Ez abszolút nem volt része a feladatnak, és bár tök fasza hogy szántál rá időt, de mivel elég sok energiát elvesz a review, nem reviewznék le még egy komplett classt és a tesztjeit teljesen feleslegesen. Ezt gondolom te is megérted. Szerintem erről beszéljünk a szerdai meetingen hogy mi legyen vele, legyen -e rá új task, van -e rá szükség, hogy kerül ez a képbe egyáltalán, mert nem triviális, befolyásolja Talent is, ez Item is egyszerre meg annál több is, befolyásolja a defense-et stb. stb. stb. Addig is a helyedben (ha ki akarod pörgetni az Armor_Types-ot) akkor kiraknám lokálisan egy külön branchre, vagy elmenteném valahova későbbi használatra, mert tök jó hogy ez megvan, csak nem most jött el az ideje hogy ezt ilyen formában berakjuk, pláne úgy hogy ez fölött is tudnék fél órát-órát ücsörögni.

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +	ARMOR_TYPE(Armors.class), SHIELDS(Shields.class);
SHIELDS-et egyelőre légyszi vedd ki (lásd a Shelds.java-hoz írt indoklásomat)

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ShieldsUnitTests.java
> +package unit_test.character_sheet_unit_tests;
Ezt nem fogom reviewzni, mentsd el későbbre, lásd Shields.java

2017-04-11 23:23 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/test_suits/CharacterSheetTestSuite.java
> +		LanguagesUnitTests.class, ArmorsUnitTests.class, ShieldsUnitTests.class })
ShieldsUnitTests-et remove-old egyelőre, lásd Shields.java-nál a commentem (importot se feledd)

2017-04-12 08:30 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/BaseClasses.java
> +	WARRIOR(Armors.LIGHT_MAIL), ROGUE(Armors.LIGHT_LEATHER), MAGE(Armors.NONE);
Igazad van ezt elnéztem. Javítva.

2017-04-12 08:32 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/BaseClasses.java
> +	private final Armors armor;
Átnevezve.

2017-04-12 08:32 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +	HEAVY_PLATE(10, -5, 150), LIGHT_LEATHER_DUSTER(3, 0, 15), TAILORED_LEATHER_DUSTER(4, 0, 45), NONE(0, 0, 0);
Átnevezve. De majd erről is értekezzünk meetingen.

2017-04-12 08:34 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(Armors.class, Armors.LIGHT_MAIL);
Kész.

2017-04-12 08:35 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +	private final int cost;
Kitöröltem őket.

2017-04-12 08:42 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		characterSheet.setData(Fields.ARMOR_TYPE, Armors.LIGHT_PLATE);
Oké, kész van.

2017-04-12 08:43 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(Armors.LIGHT_MAIL, actualValue);
Megvan. Szerencsére a testek se futnának ha csak az egyik helyen lenne átírva.

2017-04-12 08:45 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testSetArmorForWarrior() {
Azt tesztelem, hogy a default értékét felül tudom e írni neki.

2017-04-12 08:53 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(-3, actualValue + Armors.class.cast(characterSheet.getData(Fields.ARMOR_TYPE)).getArmorPenalty());
Átírtam.
Progfájlban hagytam TODO-kat ezzel kapcsolatban. Veszek rá fel taskot.

2017-04-12 08:58 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testGetCostArmorForWarrior() {
Törölve.

2017-04-12 09:00 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/GetDefaultValuesUnitTest.java
> +		assertEquals(Armors.LIGHT_MAIL, defaultCharacterSheet.getData(Fields.ARMOR_TYPE));
Kész.

2017-04-12 09:54 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Shields.java
> +package rpg_database.character_sheet;
Csináltam rá új taskot.

2017-04-12 09:54 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	public void testGetDefaultDefenseAnderSurvivor() {
Kész.

2017-04-12 09:54 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/CharacterSheet.java
> +		defaultData.put(Shields.class, Shields.NONE);
ok.

2017-04-12 09:55 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Fields.java
> +	ARMOR_TYPE(Armors.class), SHIELDS(Shields.class);
ok.

2017-04-12 09:55 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ShieldsUnitTests.java
> +package unit_test.character_sheet_unit_tests;
ok

2017-04-12 09:55 UTC, Pluci commented on RPGManager_development/test/unit_test/test_suits/CharacterSheetTestSuite.java
> +		LanguagesUnitTests.class, ArmorsUnitTests.class, ShieldsUnitTests.class })
ok.

2017-04-12 10:28 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +	// TODO Later, we should revise the set method, because it'll depends on,
Grammarnazi: it'l depend on

2017-04-12 11:14 UTC, Grandmagic13 requested changes
Ne haragudj második ránézésre még belefutottam egy-két dologba amit szerintem nem ártana megbeszélni. Lásd a kommenteket. Viszont a kód az szép, szóval inkább főleg szemantikai problémákat látok.

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +package unit_test.character_sheet_unit_tests;
Azt teszteled hogy felül tudod -e írni az armor ratingjét egy karakterlapnak miután beállítottál egy armor type-ot? Írok egy példát: Anselmnek heavy plate-je van, aminek a ratingje 10 ugye. De én adok neki egy custom made armor-t a shiny motherfucking supergoldheavyplate-et, aminek 12-es ratingje van. Felül tudja írni?

Itt felmerül az a kérdés ami most másodszori átnézésre felugrott bennem, hogy miért nem állítod az ARMOR_TYPE beállításával az ARMOR_RATING-et is, hogy azt aztán csak szimplán kívülről felül lehessen csapni az ARMOR_TYPE megváltoztatása nélkül.

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +		characterSheet.characterData.put(Fields.ARMOR_TYPE, this);
Bocs, úgy tűnik másodszori átnézésre több kérdés is felmerül bennem:
Itt miért indokolt a custom setter? Ezt sima setteren keresztül is lehetne amit a characterSheet tud. Viszont cserébe ha már az ARMOR_RATING-et is állítanád vele, akkor indokolt lenne, amit lejjebb írtam. És lehet hogy azt viszont kellene...

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +package rpg_database.character_sheet;
Igaz, hogy a cost-ot kivetettem veled, viszont lehet jó lenne ha az ARMOR_TYPE tudná magáról hogy mekkora strain-t okoz magic usereknek. Elvileg a magic rész alatt ott van az adott armor típusok által okozott terhelés, ami ugye extra mana costot jelent egy magic usernek ha armort hord. Nyilván ezt csak fel kell venni meg tudni kell gettelni, majd hogy hogyan használjuk az később kialakul, de tuti kelleni fog...
Akár fel lehetne venni egy STRAIN nevű Fields enumot amit alapból 0-ra állítunk, ARMOR_TYPE állítással állítódik az is, és nyilván csak magic-usereknél vizsgálnánk az értékét. Erről is beszélhetünk este. Lehet ez egy külön task lenne. Beszéljük meg, nem kötelezlek rá hogy ennek a keretein belül implementáld. Nem gondoltunk rá időben.

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorRatingDefaultContentTests.java
> +package unit_test.character_sheet_unit_tests;
Ez fasza :) Az említett Armor strain defaultjait is lehetne itt tesztelni, ha nincs ellenedre implementálni. Este megbeszéljük.

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	private void expectExceptionWithMessage(Class<? extends Exception> exceptionClass, String message) {
Én a privát függvényeket egy `//private functions` comment alá szoktam gyűjtögetni a file legalján tesztek esetén, hogy ne kavarjon be. Így szépen rendezetten lehet tartani a file-t.

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	// default ArmorRating for BaseClasses
Ezeknél a teszteknél az ARMOR_RATING-nek kellene már tartalmaznia az ARMOR_TYPE ratingjét. Ergo úgy kellene megoldanod, hogy
```java
assertEquals(4, actualArmorValue + characterSheet.<Armors>getData(Fields.ARMOR_TYPE).getArmorRating());
```
helyett az fusson le, hogy 
```java
assertEquals(4, actualArmorValue);
```

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
Itt az, hogy mely BaseClass számára állítasz be ARMOR_TYPE-ot az lényegtelen az ARMOR_TYPE settelése szempontjából nem? Erre a 3 tesztre (testSetArmorForWarrior, testSetArmorForRugue, testSetArmorForMage) miért van szükség?

2017-04-12 11:14 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
Ennek tulajdonképpen nincs köze a DEXTERITY-hez hiszen az nem változik. Az armor penalty értékét teszteled vele, de azt már teszteled a parametrizált tesztekben is. Itt mit szerettél volna csinálni? Magyarázd el, hátha tudok segíteni.

2017-04-13 13:33 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	private void expectExceptionWithMessage(Class<? extends Exception> exceptionClass, String message) {
ok.

2017-04-13 15:15 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
Későbbiek, talent addolása után lesznek fontosak, addig commentben vannak.

2017-04-13 15:18 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
törölve.

2017-04-13 15:18 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +		characterSheet.characterData.put(Fields.ARMOR_TYPE, this);
Igen, szükség van rá.

2017-04-13 15:29 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +package unit_test.character_sheet_unit_tests;
Átírtam, tökéletesen működik. Viszont, a default armor rating az 0, mivel Integer.class ként van beállítva. Ez szerinted így maradjon, legyen belőle egy class, vagy van valami ötleted hogyan lehetne  átálitani az értékét 4-re.

2017-04-13 15:29 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	// default ArmorRating for BaseClasses
ok.

2017-04-13 16:42 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorRatingDefaultContentTests.java
> +package unit_test.character_sheet_unit_tests;
kész

2017-04-13 16:46 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +package rpg_database.character_sheet;
Első fele kész. A másodikat átgondolom.

2017-04-13 18:07 UTC, Pluci commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +package rpg_database.character_sheet;
Csináltam fieldet, meg vettem is rá fel egy taskot.

2017-04-15 11:01 UTC, Grandmagic13 requested changes
Nem sok dolog van hátra már :)

2017-04-15 11:01 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
értem commenteld ki indoklásokkal, hogy melyik miért fog kelleni, bemehet egyelőre kikommentelve

2017-04-15 11:01 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +	@Test
Ezt ki lehet törölni :) majd később kell ilyen UIhoz.

2017-04-15 11:01 UTC, Grandmagic13 commented on RPGManager_development/src/rpg_database/character_sheet/Armors.java
> +package rpg_database.character_sheet;
Annyi, hogy hiányolom a CharacterSheetUnitTests.java-ban a Strainhez tartozó alap teszteket. Normál esetben primitív Fieldekre is tesztelünk egy malformed inputot meg egy set-elést. Mint ahogy egy XPnél vagy egy bármilyen másik alap típusnál tennénk.

2017-04-15 11:01 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +package unit_test.character_sheet_unit_tests;
Írok egy kommentet az ezt érintő sorhoz hogy ne kelljen ide-oda görgetnem rajta. Értem a helyzetet, ott leírom amit gondolok :) 👍

2017-04-15 11:01 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(0, actualArmorValue);
Szóval reflektálva arra hogy ugye jelenleg alapjáratban 0-ra állítja defaultban a karakterlap az armorvalue értékét, amit feljebb említettél. 2 lehetőség van:
- vagy megoldjuk, hogy le legyen ez a kivétel kezelve, mondjuk inicializálásnál egy olyasmival, hogy:
```java
private void putDefaultValueByFieldAllowedType(Fields field) {
		Class<?> allowedType = field.getAllowedClass();
		Object defaultValue;
		if (allowedType == CharacterAttribute.class) {
			defaultValue = new CharacterAttribute(0, BaseClasses.WARRIOR.isAttributeMajor(field));
		} else if (field.name().equals("ARMOR_RATING")) {
                        defaultValue = 4;
                } else {
			defaultValue = defaultData.get(allowedType);
		}
		characterData.put(field, allowedType.cast(defaultValue));
	}
```

- vagy azt is lehet hogy default esetben nem adunk armor type-ot ami ugye igazolná a nullás értéket. Persze akkor ennek az eseteit - hogy milyen módon van értelmezve az hogy egy karakteren nincs armor - kezelni kell. Vizsgálni hogy az az érték null -e stb.
- ultra slendrián megoldás: alapjáratban ROBE-ot adsz a karakterre. 0-s értéke van és alig kell valamit átírni. Persze nem elegáns... és nem is a kedvenc opcióm. Beszéljünk róla hogy ezek közül te mit támogatnál

És persze ezekhez mérten változhat itt a teszt is ugye.

2017-04-15 21:27 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(0, actualArmorValue);
Nekem az első megoldás tetszik a legjobban, ezért arra írtam át. Ha a továbbiakban több if else ág is születne, akkor majd újra gondoljuk, hogyan lehetne átdolgozni őket.

2017-04-15 22:15 UTC, Grandmagic13 requested changes

2017-04-15 22:15 UTC, Grandmagic13 commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(4, actualArmorValue);
ez a teszt redundáns: van egy ilyen a GetDefaultValuesUnitTest.java-ban is nem?

2017-04-15 23:02 UTC, Pluci commented on RPGManager_development/test/unit_test/character_sheet_unit_tests/ArmorsUnitTests.java
> +		assertEquals(4, actualArmorValue);
Törlöm akkor.

2017-04-16 17:14 UTC, Grandmagic13 approved these changes
approved

2017-04-16 17:15 UTC, merged