Fixed missing unit test in LanguagesUnitTests
Grandmagic13/RPGManager pull request #80
Opened 2017-05-03 15:34 UTC by Pluci

@Grandmagic13 

A felesleges importokat én sem értem, magától húzta be maven install után.

2017-05-07 18:35 UTC, Grandmagic13 requested changes

2017-05-07 18:35 UTC, Grandmagic13 commented on src/rpg_database/character_sheet/CharacterAttribute.java
> +		if (field.getAllowedClass() == Integer.class && value.getClass() == Integer.class) {
Így viszont az Object value az csak Integer lehet nem pedig int. Én azt szeretném ha mindkettő lehetne. Nyilván az int castolás is dob exeption-t, de ha így oldod meg, akkor az exception message-nek is tükröznie kell, hogy a probléma a value-val volt

2017-05-07 18:35 UTC, Grandmagic13 commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +		expectExceptionWithMessage(InvalidParameterException.class, "Unknown allowed field class: 'class java.lang.Integer'");
Ennek az exceptionnek nincs így értelme, hiszen pont az a baj, hogy nem Integerrel állítjuk mégis azt az üzenetet küldi hogy ne Integerrel állítsuk! Itt az exception-t meg kell változtatni úgy (illetve az exception dobás mechanikáját is, ha nagyon aprólékos megoldást akarsz) hogy a valóságot tükrözze

2017-05-07 18:35 UTC, Grandmagic13 commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +	public void testgetImplementingClass() {
testget helyett testGet

2017-05-07 18:35 UTC, Grandmagic13 commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +	public void testgetDataTypeClass() {
testget helyett testGet

2017-05-07 18:35 UTC, Grandmagic13 commented on test/unit_test/character_sheet_unit_tests/MoneyUnitTests.java
> +import static org.junit.Assert.assertArrayEquals;
itt inkább hagyjuk benne az előző importot

2017-05-07 18:35 UTC, Grandmagic13 commented on test/unit_test/character_sheet_unit_tests/SpecializationClassUnitTests.java
> +import static org.junit.Assert.assertFalse;
itt is légyszi a csillagos importtal éljünk

2017-05-14 19:19 UTC, Pluci commented on src/rpg_database/character_sheet/CharacterAttribute.java
> +		if (field.getAllowedClass() == Integer.class && value.getClass() == Integer.class) {
Átdolgozva.

2017-05-14 19:20 UTC, Pluci commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +		expectExceptionWithMessage(InvalidParameterException.class, "Unknown allowed field class: 'class java.lang.Integer'");
Űtdolgozva.

2017-05-14 19:20 UTC, Pluci commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +	public void testgetImplementingClass() {
javítva

2017-05-14 19:20 UTC, Pluci commented on test/unit_test/character_sheet_unit_tests/CharacterAttributeUnitTests.java
> +	public void testgetDataTypeClass() {
javítva

2017-05-14 19:22 UTC, Pluci commented on test/unit_test/character_sheet_unit_tests/MoneyUnitTests.java
> +import static org.junit.Assert.assertArrayEquals;
javitva

2017-05-14 19:23 UTC, Pluci commented on test/unit_test/character_sheet_unit_tests/SpecializationClassUnitTests.java
> +import static org.junit.Assert.assertFalse;
javitva

2017-05-18 18:37 UTC, Grandmagic13 approved these changes

2017-05-18 18:38 UTC, merged